source 'https://rubygems.org'
ruby '2.5.1'
gem 'karafka'

# include the basic plezi framework and server
gem 'plezi', '~>0.16.4'
## Redis servers are used to allow websocket scaling.
## Plezi can be configured to automatically use Redis for easy scaling.
# gem 'redis'
gem 'iodine', '~>0.7.36'  # may need to fix the version