sources:
  sources:
    acalog:
      location: http://adapter-acalog:4600
      poll: 86400 # 1 day
      root: subjects
    banner:
      location: http://adapter-banner:4600
      poll: 43200 # 12 hours
      root: subjects
    banner-seats:
      location: http://adapter-banner:4600/seats
      poll: 300 # 5 minutes
      root: sections
    yaml-schools:
      location: http://adapter-yaml:4600
      poll: 86400 # 1 day
      # poll: 60
      root: schools
    csv-topics:
      location: http://adapter-csv:4600
      poll: 600 # 10 minutes
      root: subjects
    textbooks:
      location: http://adapter-textbooks:4600
      poll: 86400
      root: subjects