version: '3.2'

# Yacs primary services
# Overrides for production
services:
  # Application services
  core:
    restart: unless-stopped
    environment:
      - RAILS_ENV=production

  core-consumer:
    restart: unless-stopped
    environment:
      - RAILS_ENV=production

  web:
    restart: unless-stopped

  malg:
    restart: unless-stopped

  # Dependency services
  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  nginx:
    restart: unless-stopped

  # Future/abandoned services
  # admin:
  #   restart: unless-stopped

  # notifications:
  #   restart: unless-stopped

  # users:
  #   restart: unless-stopped
  #   environment:
  #     - RAILS_ENV=production