version: '3.2'

# Yacs primary services
# Overrides for development
services:
  # Application services
  core:
    build: ./core
    environment:
      - COURSE_TOPIC_NAME=course_change
      - SECTION_TOPIC_NAME=section_change
      - RAILS_ENV=development
      - SECRET_KEY_BASE=6ae504547712ae4faf35b9d6186322cf
      - SECRET_TOKEN=cc621dab5bb79f81057a7d17c8ceea42
      - WEB_CONCURRENCY=1
      - MAX_THREADS=2
    ports:
      - "4100:4100"
    volumes:
      - ./core:/usr/src/app
    tty: true
    stdin_open: true

  core-consumer:
    build: ./core
    environment:
      - RAILS_ENV=development
      - TERM_SHORTNAME=202001
      - UNI_SHORTNAME
    volumes:
      - ./core:/usr/src/app
    tty: true
    stdin_open: true

  web:
    build: ./web
    ports:
      - "4200:4200"
    volumes:
      - "./web/src:/usr/src/app/src"
    command: "ng build --watch"

  malg:
    build: ./malg
    ports:
      - "4500:4500"
    volumes:
      - "./malg:/usr/src/app"
    environment:
      - TERM_SHORTNAME=202001
      - UNI_SHORTNAME

  # Dependency services
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - core
      - user_backend
  zookeeper:
    ports:
      - "2181:2181"

  kafka:
    ports:
     - "9094:9094"
     - "9092:9092"

  user_backend:
    build: https://github.com/YACS-RCOS/yacs-user-backend.git
    tty: true
    volumes:
      - ./user-backend:/usr/src/app/user-backend
    ports:
      - "5000:5000"
