source "https://rubygems.org"

ruby '2.6.0'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'oj'
gem 'nokogiri'
gem 'activesupport'
gem 'pry'
gem 'byebug'
gem 'pry-byebug'
gem 'httpclient'
gem 'concurrent-ruby'
