source 'https://rubygems.org'

ruby '2.6.3'

gem 'puma', '3.11.0'

gem 'rails', '5.1.4'
gem 'pg', '~> 0.21'
# gem 'sass-rails', '~> 5.0'

gem 'handlebars_assets'
gem 'sprockets-rails', :require => 'sprockets/railtie'

gem 'actionpack-page_caching'
gem 'actionpack-action_caching'
gem 'rails-observers'

# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'responders'

gem 'crono'
gem 'httpclient'

gem 'newrelic_rpm'

gem 'coveralls'

gem 'redis'
gem 'redis-rails'
gem 'redis-store', '~> 1.4.0'

gem 'karafka', '~> 1.2.1'
gem 'ruby-kafka', '~> 0.6.8'

gem 'rubyzip', '~> 1.2.1'
gem 'listen'

gem 'graphiti'
gem 'kaminari'

group :development, :test do
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-stack_explorer'
  gem 'pry-byebug', '~> 1.3.3'
  gem 'railroady'
  gem 'swagger-diff'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  # gem 'factory_girl_rails'  
  gem 'faker'
  gem 'graphiti_spec_helpers'
end

group :test do
  gem 'pickle'
  # gem 'webrat'
  gem 'database_cleaner'
  gem "capybara"
  gem "cucumber-rails", require: false
  gem "poltergeist"
  gem "selenium-webdriver"
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
