#!/bin/bash


SCRIPT=$(dirname `readlink -f "$0"`)
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $SCRIPT/../nginx/ssl/yacs.key -out $SCRIPT/../nginx/ssl/yacs.cer -subj "/C=US/ST=New York/L=Troy/O=RPI/OU=RCOS/CN=yacs.cs.rpi.edu"
