version: "1"

sources:
  sources:
    quacs:
      location: http://adapter-quacs:4600
      poll: 43200 # 12 hours
      root: subjects
    quacs-seats:
      location: http://adapter-quacs:4600/seats
      poll: 43200 # 12 hours
      root: sections
    acalog:
      location: http://adapter-acalog:4600
      poll: 86400 # 1 day
      root: subjects
    banner:
      location: http://adapter-banner:4600
      poll: 43200 # 12 hours
      root: subjects
    banner-seats:
      location: http://adapter-banner:4600/seats
      poll: 300 # 5 minutes
      root: sections
    yaml-schools:
      location: http://adapter-yaml:4600
      poll: 86400 # 1 day
      # poll: 60
      root: schools
    csv-topics:
      location: http://adapter-csv:4600
      poll: 600 # 10 minutes
      root: subjects
    textbooks:
      location: http://adapter-textbooks:4600
      poll: 86400
      root: subjects
    # admin:
    #   location: admin
    #   poll: 60 # 1 minute
    #   root: schools

priorities:
  default:
    fields:
      # - admin
      - quacs-seats
      - quacs
      - banner-seats
      - csv-topics
      - acalog
      - textbooks
      - banner
      - yaml-schools
  schools:
    existence: yaml-schools
  subjects:
    existence: yaml-schools
  listings:
    existence: quacs
    fields:
      longname:
        # - admin
        - quacs
        - csv-topics
        - acalog
        - banner
      description:
        - csv-topics
        - admin
        - acalog
  sections:
    existence: quacs
    fields:
      seats:
        # - admin
        - quacs-seats
        - quacs
        - banner-seats
        - banner
      seats_available:
        # - admin
        - quacs-seats
        - quacs
        - banner-seats
        - banner
