version: "3.2"

services:
  malg:
    links:
      - adapter-quacs
      - adapter-acalog
      - adapter-banner
      - adapter-yaml
      - adapter-csv
      - adapter-textbooks
    volumes:
      - ./pipelines/${UNI_SHORTNAME}/config/sources.yml:/usr/src/app/config/sources.yml

  adapter-quacs:
    build: ./pipelines/${UNI_SHORTNAME}/adapters/quacs-rpi
    expose:
      - "4600"
  adapter-acalog:
    build: ./pipelines/${UNI_SHORTNAME}/adapters/acalog-rpi
    expose:
      - "4600"
  adapter-banner:
    build: ./pipelines/${UNI_SHORTNAME}/adapters/banner-rpi
    expose:
      - "4600"
  adapter-yaml:
    build: ./pipelines/${UNI_SHORTNAME}/adapters/yaml-rpi
    expose:
      - "4600"
  adapter-csv:
    build: ./pipelines/${UNI_SHORTNAME}/adapters/csv-rpi
    expose:
      - "4600"
  adapter-textbooks:
    build: ./pipelines/${UNI_SHORTNAME}/adapters/textbooks-rpi
    depends_on:
      - adapter-banner
    expose:
      - "4600"
    environment:
      - EFOLLET_BOOKSTORE_ID=1461
